=== alp0057-netizen/1DAM_LM_AntonioLP/XML Tema11/ejemplo5/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="cilindrada" type="xs:decimal"></xs:element>
                                <xs:element name="caballos" type="poteciaDeCaballos"></xs:element>
                            </xs:choice>
                            <xs:element name="combustible" type="tipocombustible"></xs:element>
                            <xs:element name="precio" type="xs:string"></xs:element>
                            <xs:element name="a単o" type="tipoa単o" minOccurs="0"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="interesado" type="DNI" maxOccurs="unbounded"
                                minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="provincia" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipocombustible">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Diesel"></xs:enumeration>
            <xs:enumeration value="Gasolina"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <!-- Para poner un minimo y un maximo-->
    <xs:simpleType name="poteciaDeCaballos">
        <xs:restriction base="xs:unsignedShort">
            <xs:minExclusive value="60"></xs:minExclusive>
            <xs:maxExclusive value="180"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>
    <!-- Tipo de a単o 4 cifras-->
     <xs:simpleType name="tipoa単o">
        <xs:restriction base="xs:unsignedShort">
            <xs:totalDigits value="4"></xs:totalDigits>
        </xs:restriction>
     </xs:simpleType>
     <!-- DNI-->
      <xs:simpleType name="DNI">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
      </xs:simpleType>
</xs:schema>

=== alp0057-netizen/1DAM_LM_AntonioLP/XML Tema11/ejemplo5/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga">
    <coche matricula="6732KPC">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cilindrada>1.7</cilindrada>
        <combustible>Diesel</combustible>
        <precio>23.000€</precio>
        <año>2018</año>
        <color>negro</color>
        <interesado>33333333A</interesado>
        <interesado>33333333B</interesado>
    </coche>
    <coche matricula="6732KLC">
        <marca>Volkswaguen</marca>
        <modelo>Polo</modelo>
        <caballos>120</caballos>
        <combustible>Gasolina</combustible>
        <precio>3.000€</precio>
        <color>rojo</color>
        <interesado>33333333C</interesado>
    </coche>
    
    
</concesionario>
