<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacliente [
    <!ELEMENT listacliente (cliente)+>
    <!ELEMENT cliente (nombre, dias_de_entrega+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dias_de_entrega (#PCDATA)>
    <!ATTLIST cliente
        cif CDATA #REQUIRED>
    
]>

<listacliente>
    <cliente cif="A12345678"> <!-- Atributo-->
        <nombre>Mercasa.</nombre>
        <dias_de_entrega>Martes</dias_de_entrega>
        <dias_de_entrega>Lunes</dias_de_entrega>
        
    </cliente>

    <cliente cif="B87654321">
        <nombre >Frutas S.L.</nombre>
        <dias_de_entrega>MiÃ©rcoles</dias_de_entrega>
        <dias_de_entrega>Viernes</dias_de_entrega>
    </cliente>
</listacliente>